'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { isValidAddress } from '@/lib/stellar';

export default function VaultPage() {
  const [publicKey, setPublicKey] = useState<string | null>(null);
  const [coSignerKey, setCoSignerKey] = useState('');
  const [secretKey, setSecretKey] = useState('');
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState<{
    type: 'success' | 'error' | 'info';
    message: string;
  } | null>(null);
  const router = useRouter();

  useEffect(() => {
    const key = localStorage.getItem('stellarpay_pubkey');
    if (!key) {
      router.push('/');
      return;
    }
    setPublicKey(key);
  }, [router]);

  async function handleSetupVault(e: React.FormEvent) {
    e.preventDefault();
    setStatus(null);
    setLoading(true);

    try {
      if (!isValidAddress(coSignerKey)) {
        throw new Error('Invalid co-signer address');
      }

      if (coSignerKey === publicKey) {
        throw new Error('Co-signer cannot be the same as your address');
      }

      const isFreighter =
        localStorage.getItem('stellarpay_is_freighter') === 'true';

      if (isFreighter) {
        setStatus({
          type: 'info',
          message:
            'Vault setup requires your secret key for a one-time configuration. Freighter does not expose secret keys. Please use a testnet account generated by StellarPay for vault features.',
        });
        setLoading(false);
        return;
      }

      if (!secretKey) {
        setStatus({
          type: 'info',
          message:
            'Enter your secret key to authorize the vault conversion. This is a one-time operation.',
        });
        setLoading(false);
        return;
      }

      // Dynamic import to avoid bundling on server
      const StellarSdk = await import('@stellar/stellar-sdk');
      const { setupVaultAccount } = await import('@/lib/multisig');

      const keypair = StellarSdk.Keypair.fromSecret(secretKey);

      if (keypair.publicKey() !== publicKey) {
        throw new Error('Secret key does not match your connected wallet');
      }

      const hash = await setupVaultAccount(keypair, coSignerKey);

      setStatus({
        type: 'success',
        message: `Vault created! TX: ${hash.slice(0, 12)}... Your account now requires 2-of-2 signatures for payments.`,
      });

      // Clear secret key from state
      setSecretKey('');
    } catch (err: unknown) {
      const e = err as Error;
      setStatus({ type: 'error', message: e.message });
    } finally {
      setLoading(false);
    }
  }

  if (!publicKey) return null;

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm text-gray-500 mb-8">
        <Link href="/dashboard" className="hover:text-gray-300 transition-colors">
          Dashboard
        </Link>
        <span>→</span>
        <span className="text-white">Multi-Sig Vault</span>
      </div>

      {/* Header */}
      <div className="text-center mb-10">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-amber-600 to-orange-600 flex items-center justify-center mx-auto mb-4 shadow-lg shadow-amber-500/20">
          <svg className="w-8 h-8 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
          </svg>
        </div>
        <h1 className="text-2xl sm:text-3xl font-bold text-white mb-2">
          Create Multi-Sig Vault
        </h1>
        <p className="text-gray-400 max-w-md mx-auto">
          Convert your account into a 2-of-2 multi-signature vault.
          Both signers must approve every payment.
        </p>
      </div>

      {/* Warning Box */}
      <div className="glass-card rounded-2xl p-5 max-w-lg mx-auto mb-6 border-amber-500/20">
        <div className="flex gap-3">
          <svg className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
          </svg>
          <div>
            <p className="text-amber-300 font-medium text-sm">
              Irreversible Operation
            </p>
            <p className="text-gray-400 text-xs mt-1">
              Once converted, all payments require both signatures. Make sure
              both parties have access to their keys.
            </p>
          </div>
        </div>
      </div>

      {/* Form */}
      <div className="glass-card rounded-2xl p-6 sm:p-8 max-w-lg mx-auto">
        <form onSubmit={handleSetupVault} className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Your Address
            </label>
            <div className="w-full px-4 py-3 bg-white/[0.03] border border-white/[0.06] rounded-xl text-gray-500 font-mono text-xs break-all">
              {publicKey}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Co-Signer Public Key
            </label>
            <input
              type="text"
              value={coSignerKey}
              onChange={(e) => setCoSignerKey(e.target.value)}
              placeholder="G..."
              className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500/50 transition-all font-mono text-sm"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-300 mb-2">
              Your Secret Key
              <span className="text-gray-600 font-normal ml-1">
                (required for vault setup)
              </span>
            </label>
            <input
              type="password"
              value={secretKey}
              onChange={(e) => setSecretKey(e.target.value)}
              placeholder="S..."
              className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-amber-500/50 focus:border-amber-500/50 transition-all font-mono text-sm"
            />
            <p className="text-xs text-gray-600 mt-1">
              Used once to sign the setup transaction. Never stored.
            </p>
          </div>

          {/* Status */}
          {status && (
            <div
              className={`p-4 rounded-xl text-sm ${
                status.type === 'success'
                  ? 'bg-emerald-500/10 border border-emerald-500/30 text-emerald-400'
                  : status.type === 'error'
                  ? 'bg-red-500/10 border border-red-500/30 text-red-400'
                  : 'bg-blue-500/10 border border-blue-500/30 text-blue-400'
              }`}
            >
              {status.message}
            </div>
          )}

          <button
            type="submit"
            disabled={loading || !coSignerKey}
            className="w-full py-4 bg-gradient-to-r from-amber-600 to-orange-600 hover:from-amber-500 hover:to-orange-500 text-white rounded-xl font-semibold text-lg transition-all duration-300 shadow-lg shadow-amber-500/25 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {loading ? (
              <>
                <svg className="animate-spin h-5 w-5" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Setting Up Vault...
              </>
            ) : (
              <>
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                </svg>
                Create 2-of-2 Vault
              </>
            )}
          </button>
        </form>
      </div>
    </div>
  );
}
